# Generated by Django 4.2.3 on 2023-07-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterVideoRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default=True, max_length=50)),
                ('published_date', models.DateField()),
                ('video_title', models.CharField(max_length=100)),
                ('video_hashtags', models.CharField(max_length=100)),
                ('video_desc', models.CharField(max_length=200)),
                ('video_filename', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
