# Generated by Django 4.2.3 on 2023-07-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_mastervideorecord_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastervideorecord',
            name='video_thumbnail',
            field=models.FileField(default=True, upload_to='thumbnails/'),
        ),
    ]
