# Generated by Django 4.2.3 on 2023-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_mastervideorecord_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=True, max_length=50)),
                ('myprofilepic', models.FileField(default=True, upload_to='profile-pic/')),
            ],
        ),
    ]
